[display]
horizontal_padding = 0
vertical_padding = 3
width = 0
show_translation = "english"
translation_color = "dim"
font_size = "medium"
bold = true
border = false
rounded_border = true
source = false
modes = ["proverb", "anime"]
centered = true

