[[quote]]
japanese = "逃げちゃダメだ逃げちゃダメだ逃げちゃダメだ逃げちゃダメだ逃げちゃダメだ逃げちゃダメだ逃げちゃダメだ"
translation = "YYou mustn't run away.You mustn't run away.You mustn't run away.ou mustn't run away."
romaji = "Nigeccha dame da"
source = "Neon Genesis Evangelion"
